<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Company>湖北登灏科技有限公司</Company>
    <Copyright>©2020-2022 湖北登灏科技有限公司</Copyright>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="DH.NAgent" Version="4.24.2026.707-beta1346" />
    <PackageReference Include="Pek.MDB" Version="4.22.2026.416-beta1029" />
    <PackageReference Include="Pek.WebHook" Version="4.22.2026.616-beta0752" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

</Project>
