<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NMQTT" Version="4.13.2025.818-beta0749" />
    <PackageReference Include="DH.NStardust" Version="4.14.2025.818-beta0728" />
  </ItemGroup>

</Project>
