<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NMQTT" Version="4.0.2025.103" />
    <PackageReference Include="DH.NStardust" Version="4.0.2025.106-beta0011" />
  </ItemGroup>

</Project>
