<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NMQTT" Version="4.17.2026.130-beta1023" />
    <PackageReference Include="DH.NStardust" Version="4.17.2026.130-beta0900" />
  </ItemGroup>

</Project>
